// 13-using-d3-with-react-js/src/App.jsx
import React, { useState, useEffect, useRef } from "react"
import * as d3 from "d3"
import { getTimelineData, getScatterData } from "./utils/dummyData"

import Timeline from "./Timeline"
import ScatterPlot from "./ScatterPlot"
import Histogram from "./Histogram"
// import Timeline from "./completed/Timeline"
// import ScatterPlot from "./completed/ScatterPlot"
// import Histogram from "./completed/Histogram"

import "./styles.css"

const parseDate = d3.timeParse("%m/%d/%Y")
const dateAccessor = d => parseDate(d.date)
const temperatureAccessor = d => d.temperature
const humidityAccessor = d => d.humidity

const getData = () => ({
  timeline: getTimelineData(),
  scatter: getScatterData(),
})
const App = () => {
  const [data, setData] = useState(getData())

  useInterval(() => {
    setData(getData())
  }, 4000)

  return (
    <div className="App">
      <h1>
        Weather Dashboard
      </h1>
      <div className="App__charts">
        <Timeline
          data={data.timeline}
          xAccessor={dateAccessor}
          yAccessor={temperatureAccessor}
          label="Temperature"
        />
        <ScatterPlot
          data={data.scatter}
          xAccessor={humidityAccessor}
          yAccessor={temperatureAccessor}
          xLabel="Humidity"
          yLabel="Temperature"
        />
        <Histogram
          data={data.scatter}
          xAccessor={humidityAccessor}
          label="Humidity"
        />
      </div>
    </div>
  )
}

export default App


function useInterval(callback, delay) {
  const savedCallback = useRef();

  // Remember the latest callback.
  useEffect(() => {
    savedCallback.current = callback;
  });

  // Set up the interval.
  useEffect(() => {
    function tick() {
      savedCallback.current();
    }
    if (delay !== null) {
      let id = setInterval(tick, delay);
      return () => clearInterval(id);
    }
  }, [delay]);
}

// 14-using-d3-with-angular/src/app/app.component.ts
import 'zone.js'
import { Component } from '@angular/core'
import * as d3 from "d3"
import { getTimelineData, getScatterData } from "./utils/dummyData"
import { AccessorType } from './utils/types';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  timelineData: Array<timelineDataPoint>
  scatterData: Array<scatterDataPoint>

  parseDate: (value: string) => object
  dateAccessor: AccessorType
  temperatureAccessor: AccessorType
  humidityAccessor: AccessorType

  constructor() {
    this.timelineData = []
    this.scatterData = []
  }

  ngOnInit() {
    this.parseDate = d3.timeParse("%m/%d/%Y")
    this.dateAccessor = d => this.parseDate(d.date)
    this.temperatureAccessor = d => d.temperature
    this.humidityAccessor = d => d.humidity
    this.getData()
    setInterval(() => this.getData(), 4000)
  }


  getData(): void {
    this.timelineData = getTimelineData()
    this.scatterData = getScatterData()
  }
}

interface timelineDataPoint {
  date: string
  temperature: number
  key: any
}

interface scatterDataPoint {
  temperature: number
  humidity: number
  key: any
}
<div class="App">
    <h1>Weather Dashboard</h1>

    <div class="charts">
        <app-timeline
            [data]="timelineData"
            [xAccessor]="dateAccessor"
            [yAccessor]="temperatureAccessor"
            label="Temperature">
        </app-timeline>
        <app-scatter
            [data]="scatterData"
            [xAccessor]="humidityAccessor"
            [yAccessor]="temperatureAccessor"
            xLabel="Humidity"
            yLabel="Temperature">
        </app-scatter>
        <app-histogram
            [data]="scatterData"
            [xAccessor]="humidityAccessor"
            label="Humidity">
        </app-histogram>
    </div>
</div>
