// 14-using-d3-with-angular/src/app/completed/histogram/histogram.component.ts
import { Component, Input, ViewChild, ElementRef, AfterContentInit, OnChanges, SimpleChanges, HostListener } from '@angular/core'
import * as d3 from "d3"
import { DimensionsType, getUniqueId } from '../chart/utils';
import { ScaleType, AccessorType } from '../../utils/types';

@Component({
  selector: 'app-histogram',
  templateUrl: './histogram.component.html',
  styleUrls: ['./histogram.component.css'],
})
export class HistogramComponent implements AfterContentInit, OnChanges {
  @Input() data: Array<object>
  @Input() label: string
  @Input() xAccessor: AccessorType
  public dimensions: DimensionsType
  public xAccessorScaled: AccessorType
  public yAccessorScaled: AccessorType
  public xScale: ScaleType
  public yScale: ScaleType
  public widthAccessorScaled: AccessorType
  public heightAccessorScaled: AccessorType
  public keyAccessor: AccessorType
  public bins: object[]
  public gradientId: string = getUniqueId("Histogram-gradient")
  public gradientColors: string[] = ["#9980FA", "rgb(226, 222, 243)"]
  @ViewChild('container', {static: true}) container: ElementRef

  constructor() {
    this.dimensions = {
      marginTop: 40,
      marginRight: 30,
      marginBottom: 75,
      marginLeft: 75,
      height: 500,
      width: 600,
    }
    this.dimensions = {
      ...this.dimensions,
      boundedHeight: Math.max(this.dimensions.height - this.dimensions.marginTop - this.dimensions.marginBottom, 0),
      boundedWidth: Math.max(this.dimensions.width - this.dimensions.marginLeft - this.dimensions.marginRight, 0),
    }
  }

  @HostListener('window:resize') windowResize() {
    this.updateDimensions()
  }

  updateDimensions() {
    const width = this.container.nativeElement.offsetWidth
    this.dimensions.width = this.container.nativeElement.offsetWidth
    this.dimensions.boundedWidth = Math.max(this.dimensions.width - this.dimensions.marginLeft - this.dimensions.marginRight, 0)
    this.updateScales()
  }

  ngAfterContentInit() {
    this.updateDimensions()
  }

  ngOnChanges(changes: SimpleChanges): void {
    this.updateScales()
  }

  updateScales() {
    if (!this.data) return

    const numberOfThresholds = 9

    this.xScale = d3.scaleLinear()
      .domain(d3.extent(this.data, this.xAccessor))
      .range([0, this.dimensions.boundedWidth])
      .nice(numberOfThresholds)

    const binsGenerator = d3.histogram()
      .domain(this.xScale.domain())
      .value(this.xAccessor)
      .thresholds(this.xScale.ticks(numberOfThresholds))

    this.bins = binsGenerator(this.data)

    const yAccessor = d => d.length
    this.yScale = d3.scaleLinear()
      .domain([0, d3.max(this.bins, yAccessor)])
      .range([this.dimensions.boundedHeight, 0])
      .nice()

    const barPadding = 2

    this.xAccessorScaled = d => this.xScale(d.x0) + barPadding
    this.yAccessorScaled = d => this.yScale(yAccessor(d))
    this.widthAccessorScaled = d => this.xScale(d.x1) - this.xScale(d.x0) - barPadding
    this.heightAccessorScaled = d => this.dimensions.boundedHeight - this.yScale(yAccessor(d))
    this.keyAccessor = i => i
  }

}

<div #container>
  <app-chart
    [dimensions]="dimensions">
    <svg:defs>
      <svg:g appGradient
        [id]="gradientId"
        [colors]="gradientColors"
        x2="0"
        y2="100%"
      >
      </svg:g>
    </svg:defs>
    <svg:g appAxis
      dimension="x"
      [dimensions]="dimensions"
      [scale]="xScale"
      [label]="label">
    </svg:g>
    <svg:g appAxis
      dimension="y"
      [dimensions]="dimensions"
      [scale]="yScale"
      label="Count">
    </svg:g>
    <svg:g appBars
      [data]="bins"
      [keyAccessor]="keyAccessor"
      [xAccessor]="xAccessorScaled"
      [yAccessor]="yAccessorScaled"
      [widthAccessor]="widthAccessorScaled"
      [heightAccessor]="heightAccessorScaled"
      fill="url(#{{ gradientId }})">
    </svg:g>
  </app-chart>
</div>

// 13-using-d3-with-react-js/src/completed/Histogram.jsx
import React from "react"
import PropTypes from "prop-types"
import * as d3 from "d3"

import Chart from "./Chart/Chart"
import Bars from "./Chart/Bars"
import Axis from "./Chart/Axis"
import Gradient from "./Chart/Gradient"
import { useChartDimensions, accessorPropsType, useUniqueId } from "./Chart/utils"

const gradientColors = ["#9980FA", "rgb(226, 222, 243)"]
const Histogram = ({ data, xAccessor, label }) => {
  const gradientId = useUniqueId("Histogram-gradient")
  const [ref, dimensions] = useChartDimensions({
    marginBottom: 77,
  })

  const numberOfThresholds = 9

  const xScale = d3.scaleLinear()
    .domain(d3.extent(data, xAccessor))
    .range([0, dimensions.boundedWidth])
    .nice(numberOfThresholds)

  const binsGenerator = d3.histogram()
    .domain(xScale.domain())
    .value(xAccessor)
    .thresholds(xScale.ticks(numberOfThresholds))

  const bins = binsGenerator(data)

  const yAccessor = d => d.length
  const yScale = d3.scaleLinear()
    .domain([0, d3.max(bins, yAccessor)])
    .range([dimensions.boundedHeight, 0])
    .nice()

  const barPadding = 2

  const xAccessorScaled = d => xScale(d.x0) + barPadding
  const yAccessorScaled = d => yScale(yAccessor(d))
  const widthAccessorScaled = d => xScale(d.x1) - xScale(d.x0) - barPadding
  const heightAccessorScaled = d => dimensions.boundedHeight - yScale(yAccessor(d))
  const keyAccessor = (d, i) => i

  return (
    <div className="Histogram" ref={ref}>
      <Chart dimensions={dimensions}>
        <defs>
          <Gradient
            id={gradientId}
            colors={gradientColors}
            x2="0"
            y2="100%"
          />
        </defs>
        <Axis
          dimensions={dimensions}
          dimension="x"
          scale={xScale}
          label={label}
        />
        <Axis
          dimensions={dimensions}
          dimension="y"
          scale={yScale}
          label="Count"
        />
        <Bars
          data={bins}
          keyAccessor={keyAccessor}
          xAccessor={xAccessorScaled}
          yAccessor={yAccessorScaled}
          widthAccessor={widthAccessorScaled}
          heightAccessor={heightAccessorScaled}
          style={{fill: `url(#${gradientId})`}}
        />
      </Chart>
    </div>
  )
}

Histogram.propTypes = {
  xAccessor: accessorPropsType,
  yAccessor: accessorPropsType,
  xLabel: PropTypes.string,
  yLabel: PropTypes.string,
}

Histogram.defaultProps = {
  xAccessor: d => d.x,
  yAccessor: d => d.y,
}
export default Histogram
