// 14-using-d3-with-angular/src/app/completed/timeline/timeline.component.ts
import { Component, Input, ViewChild, ElementRef, AfterContentInit, OnChanges, SimpleChanges, HostListener } from '@angular/core'
import * as d3 from "d3"
import { getUniqueId } from '../chart/utils'
import { DimensionsType, ScaleType, AccessorType } from '../../utils/types'

@Component({
  selector: 'app-timeline',
  templateUrl: './timeline.component.html',
  styleUrls: ['./timeline.component.css'],
})
export class TimelineComponent implements AfterContentInit, OnChanges {
  @Input() data: Array<object>
  @Input() label: string
  @Input() xAccessor: AccessorType
  @Input() yAccessor: AccessorType
  public dimensions: DimensionsType
  public xScale: ScaleType
  public yScale: ScaleType
  public xAccessorScaled: AccessorType
  public yAccessorScaled: AccessorType
  public y0AccessorScaled: AccessorType
  public formatDate: (date: object) => string = d3.timeFormat("%-b %-d")
  public gradientId: string = getUniqueId("Timeline-gradient")
  public gradientColors: string[] = ["rgb(226, 222, 243)", "#f8f9fa"]
  @ViewChild('container', {static: true}) container: ElementRef

  constructor() {
    this.dimensions = {
      marginTop: 40,
      marginRight: 30,
      marginBottom: 75,
      marginLeft: 75,
      height: 300,
      width: 600,
    }
    this.dimensions = {
      ...this.dimensions,
      boundedHeight: Math.max(this.dimensions.height
        - this.dimensions.marginTop
        - this.dimensions.marginBottom, 0),
      boundedWidth: Math.max(this.dimensions.width
        - this.dimensions.marginLeft
        - this.dimensions.marginRight, 0),
    }
  }

  @HostListener('window:resize') windowResize() {
    this.updateDimensions()
  }

  updateDimensions() {
    const width = this.container.nativeElement.offsetWidth
    this.dimensions.width = width
    this.dimensions.boundedWidth = Math.max(
      this.dimensions.width
        - this.dimensions.marginLeft
        - this.dimensions.marginRight,
      0
    )
    this.updateScales()
  }

  ngAfterContentInit() {
    this.updateDimensions()
  }

  ngOnChanges(changes: SimpleChanges): void {
    this.updateScales()
  }

  updateScales() {
    this.xScale = d3.scaleTime()
      .domain(d3.extent(this.data, this.xAccessor))
      .range([0, this.dimensions.boundedWidth])

    this.yScale = d3.scaleLinear()
      .domain(d3.extent(this.data, this.yAccessor))
      .range([this.dimensions.boundedHeight, 0])
      .nice()

    this.xAccessorScaled = d => this.xScale(this.xAccessor(d))
    this.yAccessorScaled = d => this.yScale(this.yAccessor(d))
    this.y0AccessorScaled = this.yScale(this.yScale.domain()[0])
  }

}

<div #container>
  <app-chart
    [dimensions]="dimensions">
    <svg:defs>
      <svg:g appGradient
        [id]="gradientId"
        [colors]="gradientColors"
        x2="0"
        y2="100%"
      >
      </svg:g>
    </svg:defs>
    <svg:g appAxis
      dimension="x"
      [dimensions]="dimensions"
      [scale]="xScale"
      [formatTick]="formatDate"
      [label]="label">
    </svg:g>
    <svg:g appAxis
      dimension="y"
      [dimensions]="dimensions"
      [scale]="yScale"
      [label]="label">
    </svg:g>
    <svg:g appLine
      type="area"
      [data]="data"
      [xAccessor]="xAccessorScaled"
      [yAccessor]="yAccessorScaled"
      [y0Accessor]="y0AccessorScaled"
      fill="url(#{{ gradientId }})">
    </svg:g>
    <svg:g appLine
      [data]="data"
      [xAccessor]="xAccessorScaled"
      [yAccessor]="yAccessorScaled">
    </svg:g>
  </app-chart>
</div>

// 13-using-d3-with-react-js/src/completed/Timeline.jsx
import React from "react"
import PropTypes from "prop-types"
import * as d3 from "d3"

import Chart from "./Chart/Chart"
import Line from "./Chart/Line"
import Axis from "./Chart/Axis"
import Gradient from "./Chart/Gradient";
import { useChartDimensions, accessorPropsType, useUniqueId } from "./Chart/utils"

const formatDate = d3.timeFormat("%-b %-d")
const gradientColors = ["rgb(226, 222, 243)", "#f8f9fa"]

const Timeline = ({ data, xAccessor, yAccessor, label }) => {
  const [ref, dimensions] = useChartDimensions()
  const gradientId = useUniqueId("Timeline-gradient")

  const xScale = d3.scaleTime()
    .domain(d3.extent(data, xAccessor))
    .range([0, dimensions.boundedWidth])

  const yScale = d3.scaleLinear()
    .domain(d3.extent(data, yAccessor))
    .range([dimensions.boundedHeight, 0])
    .nice()

  const xAccessorScaled = d => xScale(xAccessor(d))
  const yAccessorScaled = d => yScale(yAccessor(d))
  const y0AccessorScaled = yScale(yScale.domain()[0])

  return (
    <div className="Timeline" ref={ref}>
      <Chart dimensions={dimensions}>
        <defs>
          <Gradient
            id={gradientId}
            colors={gradientColors}
            x2="0"
            y2="100%"
          />
        </defs>
        <Axis
          dimension="x"
          scale={xScale}
          formatTick={formatDate}
        />
        <Axis
          dimension="y"
          scale={yScale}
          label={label}
        />
        <Line
          type="area"
          data={data}
          xAccessor={xAccessorScaled}
          yAccessor={yAccessorScaled}
          y0Accessor={y0AccessorScaled}
          style={{fill: `url(#${gradientId})`}}
        />
        <Line
          data={data}
          xAccessor={xAccessorScaled}
          yAccessor={yAccessorScaled}
        />
      </Chart>
    </div>
  )
}

Timeline.propTypes = {
    xAccessor: accessorPropsType,
    yAccessor: accessorPropsType,
    label: PropTypes.string,
}

Timeline.defaultProps = {
    xAccessor: d => d.x,
    yAccessor: d => d.y,
}
export default Timeline
