// 13-using-d3-with-react-js/src/completed/Chart/Circles.jsx
import React from "react"
import PropTypes from "prop-types"
import { accessorPropsType } from "./utils";

const Circles = ({ data, keyAccessor, xAccessor, yAccessor, radius }) => (
  <React.Fragment>
    {data.map((d, i) => (
      <circle
        className="Circles__circle"
        key={keyAccessor(d, i)}
        cx={xAccessor(d, i)}
        cy={yAccessor(d, i)}
        r={typeof radius == "function" ? radius(d) : radius}
      />
    ))}
  </React.Fragment>
)

Circles.propTypes = {
  data: PropTypes.array,
  keyAccessor: accessorPropsType,
  xAccessor: accessorPropsType,
  yAccessor: accessorPropsType,
  radius: accessorPropsType,
}

Circles.defaultProps = {
  radius: 5,
}

export default Circles

// 14-using-d3-with-angular/src/app/completed/chart/circles/circles.component.ts
import { Component, Input } from '@angular/core'
import { AccessorType } from '../../../utils/types'

@Component({
  selector: '[appCircles]',
  template: `
    <svg:circle
      *ngFor="let circle of data; trackBy: keyAccessor"
      [attr.cx]="xAccessor(circle, $index)"
      [attr.cy]="yAccessor(circle, $index)"
      [attr.r]="radius">
    </svg:circle>
  `,
  styleUrls: ['./circles.component.css']
})
export class CirclesComponent {
  @Input() data: object[]
  @Input() keyAccessor: AccessorType
  @Input() xAccessor: AccessorType
  @Input() yAccessor: AccessorType
  @Input() radius?: number = 5
}
