// 13-using-d3-with-react-js/src/completed/Chart/Chart.jsx
import React, { createContext, useContext } from "react"
import { dimensionsPropsType } from "./utils"

import "./Chart.css"

const ChartContext = createContext()
export const useChartDimensions = () => useContext(ChartContext)

const Chart = ({ dimensions, children }) => (
  <ChartContext.Provider value={dimensions}>
    <svg className="Chart" width={dimensions.width} height={dimensions.height}>
      <g transform={`translate(${dimensions.marginLeft}, ${dimensions.marginTop})`}>
        { children }
      </g>
    </svg>
  </ChartContext.Provider>
)

Chart.propTypes = {
  dimensions: dimensionsPropsType
}

Chart.defaultProps = {
  dimensions: {}
}

export default Chart

// 14-using-d3-with-angular/src/app/completed/chart/chart.component.ts
import { Component, Input } from '@angular/core';
import { DimensionsType } from './../../utils/types';

@Component({
  selector: 'app-chart',
  templateUrl: './chart.component.html',
  styleUrls: ['./chart.component.css']
})
export class ChartComponent {
  @Input() dimensions: DimensionsType
}

<svg [attr.height]="dimensions.height" [attr.width]="dimensions.width">
  <svg:g [style.transform]="[
    'translate(',
    dimensions.marginLeft,
    'px, ',
    dimensions.marginTop,
    'px)'
  ].join('')">
    <ng-content></ng-content>
  </svg:g>
</svg>
